#BUNGEEBULLHORN CONFIGURATION
#KAZUHA AYATO 2022
#V1.3
format: "&8[&f全服喊话&8][&3%server%&8]&7%player% &8: &f%message%"
#可用变量：
#%server% 玩家所在子服
#%player% 玩家名
#%message% 玩家发的消息
#%playerDisplayName% 玩家显示名称 (开发中)
at:
  enabled: true
  #输入 @<指定玩家> 触发 (e.g. @_FrkNB_)
  all: true
  #输入 @all 或者 @全体 触发
  titlemsg: "&4&l有人@你"
private:
  enabled: true
  cooldown: 3
  format: "&f &l::&dPM &8[&a%sender% &f-> &e%reciever%&8] &8: &f%message%"
#可用变量：
#%server% 玩家所在子服(sender)
#%sender% 发送者
#%receiver% 目标
#%message% 发的消息
cooldown: 5
cooldownmsg: "&c你需要等待%cd%秒后才能使用这个命令！"
#可用变量:
#%consolename% 操控人名（/bbh setchar)
#%message%消息
teleport: true
#是否开启点击传送？
command: hh
#喊话指令?
disabled-servers:
  - disabledserverhere
server-groups:
  group1:
    displayname: "起床战争"
    servers:
      - bw-1
      - bw-2
      - bw-3
      - bw-4
      - bwhub
    teleport-server: bwhub
    #如果teleport-server = none
    #那么禁用，直接传送到玩家所在服务器
  group2:
    displayname: "空岛战争"
    servers:
      - sw-1
      - sw-2
      - sw-3
      - sw-4
    teleport-server: swhub